'use client';

import { useState } from 'react';
import { UserPlus, CheckCircle, AlertCircle, Copy, Eye, EyeOff } from 'lucide-react';

export default function InviteCreatorPage() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState<{ name: string; email: string; password: string } | null>(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const generatePassword = () => { const chars = 'ABCDEFGHJKLMNPQRTUVYZabcdefghjkmnpqrstuvwxyz23456789'; let pwd = ''; for (let i = 0; i < 10; i++) { pwd += chars.charAt(Math.floor(Math.random() * chars.length)); } setPassword(pwd); setShowPassword(true); };
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); setError(''); setSuccess(null); try { const res = await fetch('/api/invite-creator', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email, password }) }); const data = await res.json(); if (!res.ok) { setError(data.error || 'Failed'); setLoading(false); return; } setSuccess({ name, email, password }); setName(''); setEmail(''); setPassword(''); } catch (err: any) { setError(err.message || 'Something went wrong'); } finally { setLoading(false); } };
  const copyCredentials = () => { if (!success) return; navigator.clipboard.writeText(`Login for ${success.name}\nEmail: ${success.email}\nPassword: ${success.password}\nLogin: https://resurge-app.vercel.app/login`); setCopied(true); setTimeout(() => setCopied(false), 2000); };
  return (<div className="p-6 max-w-lg"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 bg-purple-600 rounded-lg flex items-center justify-center"><UserPlus className="w-5 h-5 text-white" /></div><div><h1 className="text-2xl font-bold text-white">Invite Creator</h1><p className="text-sm text-gray-400">Create a login for a new model / creator</p></div></div>
{success && (<div className="bg-green-500/10 border border-green-500/30 rounded-xl p-5 mb-6"><div className="flex items-center gap-2 mb-3"><CheckCircle className="w-5 h-5 text-green-400" /><span className="text-green-400 font-semibold">Account Created!</span></div><div className="space-y-2 mb-4"><p className="text-sm text-gray-300"><span className="text-gray-500">Name:</span> {success.name}</p><p className="text-sm text-gray-300"><span className="text-gray-500">Email:</span> {success.email}</p><p className="text-sm text-gray-300"><span className="text-gray-500">Password:</span> {success.password}</p></div><button onClick={copyCredentials} className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg text-sm font-medium"><Copy className="w-4 h-4" />{copied ? 'Copied!' : 'Copy Credentials'}</button></div>)}
{error && (<div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 mb-6 flex items-center gap-2"><AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0" /><p className="text-sm text-red-400">{error}</p></div>)}
<form onSubmit={handleSubmit} className="bg-[#1a1a2e] rounded-xl border border-white/10 p-6 space-y-4"><div><label className="block text-sm font-medium text-gray-300 mb-1">Creator Name</label><input type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Jessica Rivera" className="w-full px-3 py-2 bg-[#0f0f1a] border border-white/10 rounded-lg text-white text-sm placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent" required /></div><div><label className="block text-sm font-medium text-gray-300 mb-1">Email</label><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="jessica@example.com" className="w-full px-3 py-2 bg-[#0f0f1a] border border-white/10 rounded-lg text-white text-sm placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent" required /></div><div><label className="block text-sm font-medium text-gray-300 mb-1">Password</label><div className="flex gap-2"><div className="relative flex-1"><input type={showPassword ? 'text' : 'password'} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Min 6 characters" className="w-full px-3 py-2 bg-[#0f0f1a] border border-white/10 rounded-lg text-white text-sm placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent pr-10" required minLength={6} /><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300">{showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button></div><button type="button" onClick={generatePassword} className="px-3 py-2 border border-white/10 text-gray-300 rounded-lg text-xs font-medium hover:bg-white/5 whitespace-nowrap">Generate</button></div></div>
<button type="submit" disabled={loading || !name || !email || !password} className="w-full px-4 py-2.5 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg text-sm font-medium flex items-center justify-center gap-2"><UserPlus className="w-4 h-4" />{loading ? 'Creating Account...' : 'Create Creator Account'}</button></form>
<p className="text-xs text-gray-500 mt-4">The creator will log in at resurge-app.vercel.app/login and only see reels you assign to them.</p></div>);}
